defaultChannelUUID: ''
privateMessageFormatSender: '[&bTo %receiver-prefix%&b%receiver%%receiver-suffix%:](&7%date% %time%) %msg%'
privateMessageFormatReceiver: '[&dFrom %sender-prefix%&d%sender%%sender-suffix%:](&7%date% %time%) %msg%'
dateFormat: 'yyyy-MM-dd'
timeFormat: 'HH:mm:ss'
language: 'en'
serverDefaultChannels: {}

mongo:
   use: false
   host: localhost
   port: 27017
   user:
   pwd:
   authdb: admin
   db: channels
   channelCollection: channels
   chatterCollection: chatters